# pipeline.yaml — machine-readable task graph for the automated pipeline.
# Add tasks here when ready for automation. Scripts update status fields.
#
# Statuses: pending → planned → ready → done → accepted
#           pending → planned → ready → failed
#
# Fields:
#   id          — global integer, unique across all phases (required)
#   phase       — integer, for display/grouping only (required)
#   name        — task name (required)
#   description — optional detail, maps to roadmap description
#   deps        — list of task IDs that must be done or accepted before plannable (default [])
#   status      — pending | planned | ready | done | accepted | failed (default pending)

tasks:
  # Phase 2 tasks — all accepted
  - id: 1
    phase: 2
    name: Move parts by dragging
    status: accepted

  - id: 2
    phase: 2
    name: Snap-to-grid
    status: accepted

  - id: 3
    phase: 2
    name: Adjustable floor/grid size
    status: accepted

  - id: 4
    phase: 2
    name: Camera pan
    status: accepted

  - id: 5
    phase: 2
    name: Camera preset views
    status: accepted

  - id: 6
    phase: 2
    name: Editable properties panel
    status: accepted

  - id: 7
    phase: 2
    name: Board rotation on all 3 axes
    deps: [6]
    status: accepted

  - id: 8
    phase: 2
    name: Color picker
    deps: [6]
    status: accepted

  - id: 9
    phase: 2
    name: Duplicate a part
    status: accepted

  - id: 10
    phase: 2
    name: Part list/outliner
    status: accepted

  - id: 11
    phase: 2
    name: Hide/show parts
    deps: [10]
    status: accepted

  - id: 12
    phase: 2
    name: Undo/redo
    deps: [6, 7, 8, 9]
    status: accepted

  - id: 13
    phase: 2
    name: Fix editable properties panel
    deps: [6]
    status: accepted

  - id: 14
    phase: 2
    name: Fix Delete key in text inputs
    deps: [6]
    status: accepted

  - id: 15
    phase: 2
    name: Float parts list on left side
    deps: [10]
    status: accepted

  - id: 16
    phase: 2
    name: Help pane
    status: accepted

  - id: 17
    phase: 2
    name: Grid controls pane
    deps: [3]
    status: accepted

  - id: 18
    phase: 2
    name: Bug: decimal input in properties panel
    deps: [6, 13]
    status: accepted

  - id: 19
    phase: 2
    name: Bug: color picker shows black on first selection
    deps: [8]
    status: accepted

  - id: 20
    phase: 2
    name: Bug: help panel z-index behind parts list
    deps: [15, 16]
    status: accepted

  - id: 21
    phase: 2
    name: Position inputs in properties panel
    deps: [6]
    status: accepted

  - id: 22
    phase: 2
    name: Audit
    deps: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]
    status: accepted

  # Phase 3 tasks
  - id: 23
    phase: 3
    name: Assembly data model and grouping
    description: An Assembly is a named group with a position (a Three.js Group node). Parts belong to an assembly. Moving the assembly moves all its parts. The outliner shows assemblies with their parts nested inside. No single part is the parent — the assembly itself is the anchor.
    deps: []
    status: done
  - id: 28
    phase: 3
    name: Multi-select in outliner
    description: Shift+click and Cmd+click on part rows in the outliner to select multiple parts. Selection is outliner-only for now — clicking in the 3D viewport still selects a single part.
    deps: []
    status: ready
  - id: 29
    phase: 3
    name: Assembly UI — create, assign, remove
    description: "New Assembly" button in the outliner creates an empty named assembly. Drag part rows onto an assembly row to add them. Cmd+G groups the current outliner multi-selection into a new assembly. Right-click a part row to remove it from its assembly.
    deps: [23, 28]
    status: pending

  - id: 30
    phase: 3
    name: Assembly selection and movement
    description: Clicking an assembly row in the outliner selects the assembly — panel shows the assembly position, dragging in the 3D viewport moves the whole group. Clicking a part row selects just that part. Single-click in the 3D viewport selects the part; double-click selects the assembly the part belongs to (if any).
    deps: [29]
    status: pending

  - id: 31
    phase: 3
    name: Update help panel with all keyboard shortcuts and click behaviors
    description: Rewrite the help panel so every shortcut and interaction is listed one rule per line. Must include all existing shortcuts (Left-drag to draw, Right-drag to orbit, Middle/Shift-drag to pan, Scroll to zoom, Delete to delete, Escape to deselect, Cmd+D to duplicate, Cmd+Z/Cmd+Shift+Z to undo/redo, Cmd+S to save, G to toggle snap, 1/2/3/4 for camera presets) plus new assembly interactions (Cmd+G to group, single-click to select part, double-click to select assembly, click assembly row in outliner to select group, click part row in outliner to select part).
    deps: [30]
    status: pending

  - id: 25
    phase: 3
    name: Basic constraints
    description: Constraint types — flush, centered, offset by X — between pairs of parts
    deps: [30]
    status: pending

  - id: 26
    phase: 3
    name: Constraint propagation
    description: Changing one dimension updates connected parts via constraint graph
    deps: [25]
    status: pending

  - id: 27
    phase: 2
    name: Bug: drag-to-move does not update position inputs
    description: When a part is dragged to a new position, the Px/Py/Pz fields in the properties panel do not update to reflect the new position until the part is deselected and re-selected.
    deps: [21]
    status: accepted